### ISSUE TITLE
Formit issue[Edit Suggestion] Filing Bug Reports

### ISSUE THREAD

**Issue by issnteacher** [modxcms/docs#177]
## Page Title
Filing Bug Reports

## URL
https://docs.modx.com/revolution/2.x/modx-community-information/filing-bug-reports

## Issue or Suggestion
When adding a new TV the category defaults to Formit instead of None. Revo 2.5.2.

**Comment by Jako** [comment]
This is not a FormIt Issue. It is a known MODX issue and should be fixed with this commit: https://github.com/modxcms/revolution/pull/13207

Could you post your issues next time not on the docs for an extra. It belongs in the issues of the extra itself. These are mentioned in the https://docs.modx.com/extras/revo/formit#FormIt-DevelopmentandBugReporting section and should go to https://github.com/Sterc/FormIt/issues.
